# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Downloading releases
        run: |
          echo "${{ secrets.gh_token }}" | gh auth login --with-token
          git clone https://${{ secrets.gh_token }}@github.com/p3h3/DragonBMS-Interface-Chrome.git
          cd DragonBMS-Interface-Chrome
          rm -rf ./*
          gh release download --pattern '*.exe' $(gh release list -L1 | awk -F'\t' '{print $3}')
          gh release download --pattern '*.AppImage' $(gh release list -L1 | awk -F'\t' '{print $3}')
          cd ..
          gh release create v0.2.2 ./DragonBMS-Interface-Chrome/*
          echo $(ls)
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: Release-Downloads
          path: DragonBMS-Interface-Chrome
